#!/bin/sh -e

. /etc/lsb-release
wget -nc https://sourceforge.net/projects/httpfs/files/httpfs2/httpfs2-0.1.5.tar.gz
sudo apt install libfuse-dev

rm -R httpfs2-0.1.5 || true
rm -R initramfs || true

tar xfvz httpfs2-0.1.5.tar.gz
cd httpfs2-0.1.5
patch -p1 <../httpfs.patch
make httpfs2
cd ..

mkdir initramfs
cd initramfs
lzcat /cdrom/casper/initrd.lz  | cpio -i
cp ../httpfs2-0.1.5/httpfs2 sbin
cp /lib/*-linux-gnu/libfuse.so.2 lib
patch -p1 <../init.patch
patch -p1 <../casper.patch
DISTRIB_ARCH=$(arch | sed s/x86_64/amd64/)
DISTRIB_VERSION=$(echo $DISTRIB_DESCRIPTION | cut -d ' ' -f 2)
find . | cpio -o -H newc | lzma -9 -e >../${DISTRIB_CODENAME}_${DISTRIB_VERSION}_${DISTRIB_ARCH}_initrd.lz
cd ..
cp /cdrom/casper/vmlinuz* ${DISTRIB_CODENAME}_${DISTRIB_VERSION}_${DISTRIB_ARCH}_vmlinuz
